spring:
  application:
    name: yologger-sns-api
  profiles:
    active: dev

logging:
  level:
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation: OFF

core:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  slave:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.hbm2ddl.auto: none
      hibernate.jdbc.time_zone: Asia/Seoul
    show-sql: false
    database: mysql

yologger-sns:
  auth:
    jwt:
      secret: X_YOLOGGER_SNS_AUTH_TOKEN
    access-token:
      expire_in_seconds: 86400  # 1 day
